services:
  mosquitto:
    image: eclipse-mosquitto:2.0.21
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
    networks:
      - "homeassistant_network"

  homeassistant:
    image: homeassistant/home-assistant:2025.6
    container_name: homeassistant
    restart: unless-stopped
    volumes:
      - ./homeassistant:/config
    ports:
      - "8123:8123"
    networks:
      - "homeassistant_network"

networks:
  homeassistant_network:
    driver: bridge