
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt: !include mqtt_sensors.yaml
template: !include template_sensors.yaml

lovelace:
  mode: yaml
  dashboards:
    mqtt-sensors:
      mode: yaml
      title: MQTT Sensors
      icon: mdi:chip
      show_in_sidebar: true
      filename: lovelace/mqtt_dashboard.yaml

recorder:
  include:
    entities:
      - sensor.esp32_poti_voltage_graph