sensor:
  - name: "ESP32 Temperature"
    state_topic: "home/esp32/temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    unique_id: esp32_temperature
    object_id: "esp32_temperature"

  - name: "ESP32 Humidity"
    state_topic: "home/esp32/humidity"
    unit_of_measurement: "%"
    device_class: humidity
    unique_id: esp32_humidity
    object_id: "esp32_humidity"

  - name: "ESP32 Potentiometer Voltage"
    state_topic: "home/esp32/poti_voltage"
    unit_of_measurement: "V"
    device_class: voltage
    unique_id: esp32_poti_voltage
    object_id: "esp32_poti_voltage"
    value_template: "{{ value | float | round(2) }}"

  - name: "ESP32 Carbondioxide"
    state_topic: "home/esp32/carbondioxide"
    unit_of_measurement: "ppm"
    device_class: "carbon_dioxide"
    unique_id: esp32_co2
    object_id: "esp32_co2"

  - name: "ESP32 Formaldehyde"
    state_topic: "home/esp32/formaldehyde"
    unit_of_measurement: "ppb"
    state_class: measurement
    icon: mdi:biohazard
    unique_id: esp32_formaldehyde
    object_id: "esp32_formaldehyde"

  - name: "ESP32 TVOC"
    state_topic: "home/esp32/tvoc"
    unit_of_measurement: "ppm"
    state_class: measurement
    icon: mdi:biohazard
    unique_id: esp32_tvoc
    object_id: "esp32_tvoc"

  - name: "ESP32 Air Quality"
    state_topic: "home/esp32/airquality"
    icon: mdi:air-filter
    unit_of_measurement: ""
    state_class: measurement
    unique_id: esp32_airquality
    object_id: "esp32_airquality"
    value_template: "{{ value | int }}"

  - name: "ESP32 Light"
    state_topic: "home/esp32/lightsensor"
    unit_of_measurement: "lx"
    device_class: "illuminance"
    unique_id: esp32_light
    object_id: "esp32_light"